# Generated by Django 5.1.3 on 2024-11-21 17:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Docs',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('docName', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('dtRegister', models.DateField()),
            ],
        ),
    ]
