# Generated by Django 5.1.3 on 2024-11-23 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0002_docs_accepted_alter_docs_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='docs',
            name='score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='docs',
            name='dtRegister',
            field=models.DateTimeField(),
        ),
    ]
