# Generated by Django 5.1.3 on 2024-11-21 17:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('dtLog', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
