# Generated by Django 5.1.3 on 2024-11-23 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='status',
            field=models.CharField(choices=[('error', 'error'), ('arquivo negado', 'arquivo negado'), ('arquivo aceito', 'arquivo aceito')], max_length=255),
        ),
    ]
